export const TABLE_NAME = 'Section';
export const FILE_NAME = 'Section.csv';
export const COLUMNS = [
  { id: 'ActCode', title: 'ActCode' },
  { id: 'SectionCode', title: 'SectionCode' },
  { id: 'SectionDescription', title: 'SectionDescription' },
  { id: 'Active', title: 'Active' },
];

export async function generate() {
  return [
    { ActCode: 'IPC',   SectionCode: '302',  SectionDescription: 'Murder', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '304',  SectionDescription: 'Culpable Homicide not amounting to murder', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '307',  SectionDescription: 'Attempt to Murder', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '324',  SectionDescription: 'Voluntarily causing hurt by dangerous weapons', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '354',  SectionDescription: 'Assault or criminal force to woman with intent to outrage her modesty', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '363',  SectionDescription: 'Kidnapping', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '376',  SectionDescription: 'Rape', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '379',  SectionDescription: 'Theft', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '380',  SectionDescription: 'Theft in dwelling house', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '384',  SectionDescription: 'Extortion', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '392',  SectionDescription: 'Robbery', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '395',  SectionDescription: 'Dacoity', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '406',  SectionDescription: 'Criminal breach of trust', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '420',  SectionDescription: 'Cheating and dishonestly inducing delivery of property', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '435',  SectionDescription: 'Mischief by fire with intent to cause damage', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '441',  SectionDescription: 'Criminal trespass', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '447',  SectionDescription: 'Punishment for criminal trespass', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '457',  SectionDescription: 'Lurking house-trespass by night', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '489A', SectionDescription: 'Counterfeiting currency notes', Active: 'TRUE' },
    { ActCode: 'IPC',   SectionCode: '498A', SectionDescription: 'Dowry death', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '154',  SectionDescription: 'Information in cognizable offences', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '155',  SectionDescription: 'Information as to non-cognizable offences', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '157',  SectionDescription: 'Procedure for investigation', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '161',  SectionDescription: 'Examination of witnesses by police', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '164',  SectionDescription: 'Recording of confessions and statements', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '167',  SectionDescription: 'Procedure when investigation cannot be completed', Active: 'TRUE' },
    { ActCode: 'CRPC',  SectionCode: '173',  SectionDescription: 'Report of police officer on completion of investigation', Active: 'TRUE' },
    { ActCode: 'IEA',   SectionCode: '24',   SectionDescription: 'Confession caused by inducement threat or promise', Active: 'TRUE' },
    { ActCode: 'IEA',   SectionCode: '25',   SectionDescription: 'Confession to police officer not to be proved', Active: 'TRUE' },
    { ActCode: 'IEA',   SectionCode: '26',   SectionDescription: 'Confession by accused while in custody of police', Active: 'TRUE' },
    { ActCode: 'IEA',   SectionCode: '27',   SectionDescription: 'How much of information received from accused may be proved', Active: 'TRUE' },
    { ActCode: 'IEA',   SectionCode: '65B',  SectionDescription: 'Admissibility of electronic records', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '8',    SectionDescription: 'Prohibition of certain operations', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '15',   SectionDescription: 'Punishment for contravention in relation to poppy straw', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '18',   SectionDescription: 'Punishment for contravention in relation to cannabis plant', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '20',   SectionDescription: 'Punishment for contravention in relation to cannabis', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '21',   SectionDescription: 'Punishment for contravention in relation to manufactured drugs', Active: 'TRUE' },
    { ActCode: 'NDPS',  SectionCode: '22',   SectionDescription: 'Punishment for contravention in relation to psychotropic substances', Active: 'TRUE' },
    { ActCode: 'ARMS',  SectionCode: '3',    SectionDescription: 'License for acquisition and possession', Active: 'TRUE' },
    { ActCode: 'ARMS',  SectionCode: '25',   SectionDescription: 'Punishment for certain offences', Active: 'TRUE' },
    { ActCode: 'ARMS',  SectionCode: '27',   SectionDescription: 'Punishment for using arms', Active: 'TRUE' },
    { ActCode: 'ITACT', SectionCode: '43',   SectionDescription: 'Penalty for unauthorized access to computer', Active: 'TRUE' },
    { ActCode: 'ITACT', SectionCode: '66',   SectionDescription: 'Hacking with computer system', Active: 'TRUE' },
    { ActCode: 'ITACT', SectionCode: '67',   SectionDescription: 'Punishment for publishing obscene information', Active: 'TRUE' },
  ];
}
