import catalyst from 'zcatalyst-sdk-node';
import { readFileSync } from 'fs';
import { mkdir, writeFile } from 'fs/promises';
import { join, dirname, resolve } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const MAPPINGS_DIR = join(__dirname, 'mappings');
const PROJECT_ROOT = resolve(__dirname, '..');

function buildKeyFn(keyFields) {
  if (keyFields.length === 1) {
    const field = keyFields[0];
    return (record) => String(record[field]);
  }
  return (record) => keyFields.map((f) => record[f]).join('_');
}

const TABLES = [
  // Phase 1 — lookup tables (mapping filename ≠ Catalyst table name)
  { name: 'State',              keyFields: ['StateID'],            file: 'state' },
  { name: 'District',           keyFields: ['DistrictID'],         file: 'district' },
  { name: 'CaseCategory',       keyFields: ['CaseCategoryID'],     file: 'caseCategory' },
  { name: 'GravityOffence',     keyFields: ['GravityOffenceID'],   file: 'gravityOffence' },
  { name: 'CrimeHead',          keyFields: ['CrimeHeadID'],        file: 'crimeHead' },
  { name: 'CrimeSubHead',       keyFields: ['CrimeSubHeadID'],     file: 'crimeSubHead' },
  { name: 'Act',                keyFields: ['ActCode'],            file: 'act' },
  { name: 'Section',            keyFields: ['ActCode', 'SectionCode'], file: 'section' },
  { name: 'CrimeHeadActSection', keyFields: ['CrimeHeadID', 'ActCode', 'SectionCode'], file: 'crimeHeadActSection' },
  { name: 'ReligionMaster',     keyFields: ['ReligionID'],         file: 'religion' },
  { name: 'CasteMaster',        keyFields: ['caste_master_id'],    file: 'caste' },
  { name: 'OccupationMaster',   keyFields: ['OccupationID'],       file: 'occupation' },
  { name: 'CaseStatusMaster',   keyFields: ['CaseStatusID'],       file: 'caseStatus' },
  { name: 'UnitType',           keyFields: ['UnitTypeID'],         file: 'unitType' },
  { name: 'Rank',               keyFields: ['RankID'],             file: 'rank' },
  { name: 'Designation',        keyFields: ['DesignationID'],      file: 'designation' },

  // Phase 2b — org structure
  { name: 'Unit',               keyFields: ['UnitID'],             file: 'unit' },
  { name: 'Court',              keyFields: ['CourtID'],            file: 'court' },

  // Employee (generated by generate_employee.cjs)
  { name: 'Employee',           keyFields: ['EmployeeID'],         file: 'employee' },

  // Phase 4 — case data
  { name: 'CaseMaster',         keyFields: ['CaseMasterID'],       file: 'caseMaster' },

  // Phase 5 — case-dependent
  { name: 'ComplainantDetails', keyFields: ['ComplainantID'],      file: 'complainant' },
  { name: 'Victim',             keyFields: ['VictimMasterID'],     file: 'victim' },
  { name: 'Accused',            keyFields: ['AccusedMasterID'],    file: 'accused' },
  { name: 'ActSectionAssociation', keyFields: ['CaseMasterID', 'ActID', 'SectionID'], file: 'actSection' },
  { name: 'ChargesheetDetails', keyFields: ['CSID'],               file: 'chargesheet' },

  // Phase 6
  { name: 'ArrestSurrender',    keyFields: ['ArrestSurrenderID'],  file: 'arrestSurrender' },
];

async function fetchTable({ name, keyFields }, dataStore) {
  const toKey = buildKeyFn(keyFields);
  const table = dataStore.table(name);

  const mapping = {};
  let count = 0;

  for await (const row of table.getIterableRows()) {
    const key = toKey(row);
    mapping[key] = String(row.ROWID);
    count++;
  }

  return { tableName: name, mapping, count };
}

async function writeMapping({ tableName, mapping, count, file }) {
  const fileName = file || tableName;
  const filePath = join(MAPPINGS_DIR, `${fileName}.json`);
  await writeFile(filePath, JSON.stringify(mapping, null, 2));
  console.log(`✓ ${tableName} (${count} records) → ${fileName}.json`);
}

function loadCatalystConfig() {
  const rcPath = join(PROJECT_ROOT, '.catalystrc');
  const rc = JSON.parse(readFileSync(rcPath, 'utf8'));
  const proj = rc.projects[rc.actives.project - 1];
  const envObj = proj.env[rc.actives.env - 1];
  const projectKey = process.env.CATALYST_PROJECT_KEY;
  if (!projectKey) {
    throw new Error(
      'CATALYST_PROJECT_KEY env var is not set. ' +
      'Get it from Catalyst Console > Project Settings > Project Key.'
    );
  }
  return {
    project_id: proj.id,
    project_key: projectKey,
    environment: envObj.name,
  };
}

async function main() {
  const appOptions = loadCatalystConfig();
  const app = catalyst.initializeApp(appOptions);
  const dataStore = app.datastore();

  await mkdir(MAPPINGS_DIR, { recursive: true });

  for (const config of TABLES) {
    try {
      const result = await fetchTable(config, dataStore);
      await writeMapping({ ...result, file: config.file });
    } catch (err) {
      console.error(`✗ ${config.name}: ${err.message}`);
    }
  }

  console.log('\nMappings generated successfully.');
}

main().catch((err) => {
  console.error('Failed:', err);
  process.exit(1);
});
